name: Deploy Blazor to GitHub Pages

# Run workflow on every push to the master branch
on:
  push:
    branches: [ main ]
    
jobs:
  deploy-to-github-pages:
  
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Add .nojekyll file
          run: touch release/wwwroot/.nojekyll
          
        # sets up .NET Core SDK 3.1
        - name: Setup .NET Core SDK
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 5.0.401
            
        # publishes Blazor project to the release-folder
        - name: Publish .NET Core Project
          run: dotnet publish BlazorGitHubPages.csproj -c Release -o release --nologo
          
          # changes the base-tag in index.html from '/' to 'BlazorGitHubPages' to match GitHub Pages repository subdirectory
        - name: Change base-tag in index.html from / to BlazorGitHubPages
          run: sed -i 's/<base href="\/" \/>/<base href="\/BlazorGitHubPages\/" \/>/g' release/wwwroot/index.html
        - name: Commit wwwroot to GitHub Pages
          uses: JamesIves/github-pages-deploy-action@4.1.5
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages
            FOLDER: release/wwwroot
